spring:
  application:
    name:
      TeamPonyo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update
  data:
    elasticsearch:
      repositories:
        enabled: true
      url: localhost
      username: ${ELASTIC_USERNAME}
      password: ${ELASTIC_PASSWORD}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
oauth:
  naver:
    secret:
      ${NAVER_SECRET}
  kakao:
    secret:
      ${KAKAO_SECRET}
  google:
    secret:
      ${GOOGLE_SECRET}
jwt:
  secret: ${JWT_SECRET}
  access-token-expiry: 14d #TODO: 2시간...
  refresh-token-expiry: 14d
  oauth2-login-token-expiry: 10m
aws:
  bucket-name:
    ${BUCKET_NAME}
  access-key:
    ${AWS_ACCESS_KEY}
  secret-key:
    ${AWS_SECRET_KEY}