spring:
  application:
    name:
      TeamPonyo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
oauth:
  naver:
    secret:
      ${NAVER_SECRET}
  kakao:
    secret:
      ${KAKAO_SECRET}
  google:
    secret:
      ${GOOGLE_SECRET}
jwt:
  secret: ${JWT_SECRET}
  access-token-expiry: 2h
  refresh-token-expiry: 14d
  oauth2-login-token-expiry: 10m